name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run unit tests (exclude benchmarks)
        run: ctest --test-dir build --output-on-failure -E "Benchmarks|ECBLatencyBenchmark|ECBThroughputBenchmark|CBCLatencyBenchmark|CBCThroughputBenchmark"


      # - name: Run benchmarks only
      #   run: ctest --test-dir build --output-on-failure -R Benchmarks

      - name: Run ECB latency benchmark
        run: ctest --test-dir build --output-on-failure -R ECBLatencyBenchmark

      - name: Run ECB throughput benchmark
        run: ctest --test-dir build --output-on-failure -R ECBThroughputBenchmark

      - name: Run CBC latency benchmark
        run: ctest --test-dir build --output-on-failure -R CBCLatencyBenchmark

      - name: Run CBC throughput benchmark
        run: ctest --test-dir build --output-on-failure -R CBCThroughputBenchmark